pluginManagement {
    repositories {
        maven {
            name = 'groupezReleases'
            url = uri('https://repo.groupez.dev/releases')
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = 'zVeinMiner'

include 'API'

file('Hooks').listFiles()?.each { file ->
    if (file.isDirectory() && !file.name.equals('build')) {
        println "Include Hooks:${file.name}"
        include ":Hooks:${file.name}"
    }
}
